{
    'name': 'Gestion des Soutenances',
    'version': '12.0.1.0.0',
    'category': 'University',
    'summary': 'Gestion des soutenances de thèse de doctorat',
    'author': 'Aguelloul Mouad & Amina Agazzar',
    'license': 'AGPL-3',
    'depends': ['web', 'base', 'mail', 'website', 'portal'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/wizard_views.xml',
        'views/session_views.xml',
        'views/role_views.xml',
        'views/personnel_views.xml',
        'views/soutenance_views.xml',
        'views/rapporteur_proposition_views.xml',
        'views/jury_views.xml',
        'views/document_views.xml',
        'views/document_type_views.xml',
        'views/doctorant_views.xml',
        'views/diplome_views.xml',
        'views/specialite_views.xml',
        'views/discipline_views.xml',
        'views/soutenance_web_templates.xml',
        'report/layouts.xml',
        'report/paperformat.xml',
        'report/report.xml',
        'report/pv_global_report_action.xml',
        'report/formulaire_dossier_template.xml',
        'report/fiche_de_renseignement_template.xml',
        'report/attestation_jury_template.xml',
        'report/avis_soutenance_template.xml',
        'report/rapporteur_invitation_template.xml',
        'report/jury_convocation_template.xml',
        'report/attestation_reussite_doctorant_template.xml',
        'report/pv_soutenance_template.xml',
        'report/attestation_encadrement_template.xml',
        'report/attestation_participation_jury_template.xml',
        'data/mail_template_rapporteur_invitation.xml',
        'data/mail_template_jury_convocation.xml',
        'data/mail_template_refus_rapporteurs_doyen.xml',
        'data/mail_template_refus_jury_planification_doyen.xml',
        'data/mail_template_rapporteurs_directeur.xml',
        'data/mail_template_jury_directeur.xml',
    ],
    'demo': [
        'demo/demo_doctorant.xml',
    ],
    'installable': True,
    'application': True,
} 