from . import doctorant
from . import soutenance
from . import rapporteur_proposition
from . import jury
from . import document
from . import diplome
from . import document_type
from . import session
from . import personnel
from . import role
from . import specialite
from . import discipline