from . import import_rapporteurs_wizard
from . import import_jury_wizard
from . import modifier_demande_wizard
from . import rapporteur_upload_fichier_wizard
from . import rapporteur_upload_cv_wizard
from . import ajout_rapporteurs_wizard
from . import modifier_rapporteurs_wizard
from . import ajout_jury_wizard
from . import modifier_jury_wizard
from . import ajout_planification_wizard
from . import modifier_planification_wizard
from . import entrer_resultat_soutenance_wizard 
from . import confirmation_valider_rapporteurs_wizard
from . import confirmation_valider_jury_planification_wizard
from . import refus_rapporteurs_doyen_wizard
from . import refus_jury_planification_doyen_wizard
from . import refus_ced_wizard
from . import avis_commission_wizard
from . import pv_global_wizard